"""Generate and audit deterministic Phase 13 correctness and large fixtures.

Small fixtures are generated by default.  Passing ``--large`` additionally writes the
5,850,000-row CSV and Parquet fixtures.  Fixture payloads live below ``.tmp/phase13-*``;
only the JSON manifest is intended for source control.
"""

from __future__ import annotations

import argparse
import csv
import hashlib
import json
import math
import os
import platform
import shutil
import sys
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Iterable

import numpy as np
import pyarrow as pa
import pyarrow.parquet as pq


GENERATOR_VERSION = "phase13-fixtures-v1"
SEED = 20260722
LARGE_ROWS = 5_850_000
LARGE_COLUMNS = 15
LARGE_BATCH_ROWS = 50_000
PARQUET_ROW_GROUP_ROWS = 65_536
DEFAULT_OUTPUT = Path(".tmp/phase13-fixtures")
DEFAULT_MANIFEST = Path("artifacts/phase-13/fixture-manifest.json")
SMALL_LONG_BYTES = 8 * 1024 * 1024 + 17


def utc_now() -> str:
    return datetime.now(timezone.utc).isoformat()


def sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as stream:
        for chunk in iter(lambda: stream.read(8 * 1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def schema_json(schema: pa.Schema) -> list[dict[str, Any]]:
    return [
        {"name": field.name, "type": str(field.type), "nullable": field.nullable}
        for field in schema
    ]


def schema_sha256(schema: pa.Schema) -> str:
    return hashlib.sha256(schema.serialize().to_pybytes()).hexdigest()


def stable_u64(value: int, salt: int = 0) -> int:
    mixed = (value + SEED + salt) & 0xFFFF_FFFF_FFFF_FFFF
    mixed ^= mixed >> 30
    mixed = (mixed * 0xBF58_476D_1CE4_E5B9) & 0xFFFF_FFFF_FFFF_FFFF
    mixed ^= mixed >> 27
    mixed = (mixed * 0x94D0_49BB_1331_11EB) & 0xFFFF_FFFF_FFFF_FFFF
    mixed ^= mixed >> 31
    return mixed


def stable_u64_array(values: np.ndarray, salt: int = 0) -> np.ndarray:
    """Vectorized splitmix64 with the same wrapping semantics as stable_u64."""
    mixed = values.astype(np.uint64, copy=True)
    mixed += np.uint64(SEED + salt)
    mixed ^= mixed >> np.uint64(30)
    mixed *= np.uint64(0xBF58_476D_1CE4_E5B9)
    mixed ^= mixed >> np.uint64(27)
    mixed *= np.uint64(0x94D0_49BB_1331_11EB)
    mixed ^= mixed >> np.uint64(31)
    return mixed


def write_bytes(path: Path, payload: bytes) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    partial = path.with_suffix(path.suffix + ".partial")
    partial.write_bytes(payload)
    partial.replace(path)


def write_text(path: Path, text: str) -> None:
    write_bytes(path, text.encode("utf-8"))


def write_parquet(path: Path, table: pa.Table, row_group_size: int | None = None) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    partial = path.with_suffix(path.suffix + ".partial")
    partial.unlink(missing_ok=True)
    pq.write_table(
        table,
        partial,
        compression="zstd",
        compression_level=3,
        use_dictionary=True,
        row_group_size=row_group_size or max(1, table.num_rows),
        data_page_version="2.0",
    )
    partial.replace(path)


def parquet_entry(
    fixture_id: str,
    path: Path,
    profile: str,
    oracle: dict[str, Any],
) -> dict[str, Any]:
    parquet = pq.ParquetFile(path)
    schema = parquet.schema_arrow
    return {
        "id": fixture_id,
        "kind": "parquet",
        "path": path.as_posix(),
        "profile": profile,
        "rows": parquet.metadata.num_rows,
        "columns": parquet.metadata.num_columns,
        "rowGroups": parquet.metadata.num_row_groups,
        "schema": schema_json(schema),
        "schemaSha256": schema_sha256(schema),
        "bytes": path.stat().st_size,
        "sha256": sha256_file(path),
        "oracle": oracle,
        "audit": "PASS",
    }


def file_entry(
    fixture_id: str,
    path: Path,
    profile: str,
    rows: int | None,
    columns: int | None,
    oracle: dict[str, Any],
    *,
    kind: str = "csv",
    schema: list[dict[str, Any]] | None = None,
) -> dict[str, Any]:
    return {
        "id": fixture_id,
        "kind": kind,
        "path": path.as_posix(),
        "profile": profile,
        "rows": rows,
        "columns": columns,
        "schema": schema,
        "bytes": path.stat().st_size,
        "sha256": sha256_file(path),
        "oracle": oracle,
        "audit": "PASS",
    }


def make_boundary_states(root: Path) -> dict[str, Any]:
    path = root / "small" / "boundary-states-small.parquet"
    table = pa.table(
        {
            "row_id": pa.array(range(8), type=pa.int64()),
            "text_value": pa.array([None, "", " ", "x", "0", "\n", "false", "end"]),
            "int_value": pa.array([None, 0, 1, -1, None, 2, 0, 3], type=pa.int64()),
            "bool_value": pa.array([None, False, True, False, None, True, False, True]),
            "float_value": pa.array([None, 0.0, float("nan"), -0.0, 1.5, None, -2.0, 3.0]),
            "binary_value": pa.array([None, b"", b"x", b"\x00", None, b"yy", b"", b"z"]),
            "duration_ns": pa.array([None, 0, 1, -1, None, 2, 0, 3], type=pa.duration("ns")),
        }
    )
    write_parquet(path, table)
    return parquet_entry(
        "boundary-states-small",
        path,
        "typed-empty-vs-occupied",
        {
            "emptyDefinition": "null or empty string only",
            "occupied": {
                "text_value": [False, False, True, True, True, True, True, True],
                "int_value": [False, True, True, True, False, True, True, True],
                "bool_value": [False, True, True, True, False, True, True, True],
                "float_value": [False, True, True, True, True, False, True, True],
                "binary_value": [False, True, True, True, False, True, True, True],
                "duration_ns": [False, True, True, True, False, True, True, True],
            },
        },
    )


def nulls_last(value: Any) -> tuple[int, Any]:
    return (1, 0) if value is None else (0, value)


def make_boundary_query_map(root: Path) -> dict[str, Any]:
    path = root / "small" / "boundary-query-map.parquet"
    rows = list(range(200))
    # A full permutation gives scattered but unique source identities.
    source_ids = [(row * 73 + 19) % len(rows) for row in rows]
    included = [row % 3 != 0 for row in rows]
    sort_a = [None if row % 17 == 0 else row % 7 for row in rows]
    sort_b = [None if row % 19 == 0 else chr(ord("A") + row % 5) for row in rows]
    sort_c = [row % 4 for row in rows]
    table = pa.table(
        {
            "source_row_id": pa.array(source_ids, type=pa.int64()),
            "included": pa.array(included),
            "sort_a": pa.array(sort_a, type=pa.int32()),
            "sort_b": pa.array(sort_b),
            "sort_c": pa.array(sort_c, type=pa.int16()),
            "value": pa.array([None if row % 23 == 0 else ("" if row % 29 == 0 else f"v-{row % 11}") for row in rows]),
        }
    )
    write_parquet(path, table)
    filtered = [index for index in rows if included[index]]
    sorted_all = sorted(
        rows,
        key=lambda index: (
            nulls_last(sort_a[index]),
            nulls_last(sort_b[index]),
            -sort_c[index],
            source_ids[index],
        ),
    )
    filtered_sorted = [index for index in sorted_all if included[index]]
    return parquet_entry(
        "boundary-query-map",
        path,
        "filter-stable-three-sort",
        {
            "filterOnlySourceRowIds": [source_ids[index] for index in filtered],
            "sortOnlySourceRowIds": [source_ids[index] for index in sorted_all],
            "filterThenSortSourceRowIds": [source_ids[index] for index in filtered_sorted],
            "sort": ["sort_a ASC NULLS LAST", "sort_b ASC NULLS LAST", "sort_c DESC NULLS LAST", "source_row_id ASC"],
        },
    )


def make_boundary_long_string(root: Path) -> dict[str, Any]:
    path = root / "small" / "boundary-long-string.parquet"
    lengths = [0, 1, 1024, 65_537, SMALL_LONG_BYTES]
    alphabet = "0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ"
    values = [
        "" if length == 0 else (alphabet * math.ceil(length / len(alphabet)))[:length]
        for length in lengths
    ]
    table = pa.table({"row_id": range(len(values)), "payload": values})
    write_parquet(path, table)
    return parquet_entry(
        "boundary-long-string",
        path,
        "decoded-byte-cap",
        {"utf8ByteLengths": lengths, "decodeCapBytes": 8 * 1024 * 1024},
    )


def make_csv_matrix(root: Path) -> list[dict[str, Any]]:
    matrix = root / "small" / "csv-prepared-matrix"
    cases: list[tuple[str, bytes, int | None, int | None, str]] = [
        ("empty.csv", b"", 0, 0, "valid-empty"),
        ("header-only.csv", b"a,b,c\n", 0, 3, "valid-header-only"),
        ("duplicate-blank-header.csv", b"a,,a\n1,2,3\n", 1, 3, "valid-duplicate-blank-header"),
        ("quoted-lf.csv", b'a,b\n1,"two,2"\n2,"line1\nline2"\n', 2, 2, "valid-quoted-lf"),
        ("crlf-trailing.csv", b"a,b,c\r\n1,2,\r\n3,4,5\r\n", 2, 3, "valid-crlf-trailing"),
        ("tab.tsv", b"a\tb\n1\t2\n", 1, 2, "valid-tab"),
        ("semicolon.csv", b"a;b\n1;2\n", 1, 2, "valid-semicolon"),
        ("bom.csv", b"\xef\xbb\xbfa,b\n1,2\n", 1, 2, "valid-utf8-bom"),
        ("malformed.csv", b'a,b\n1,"unterminated\n', None, 2, "invalid-unclosed-quote"),
        ("invalid-utf8.csv", b"a,b\n1,\xff\n", None, 2, "invalid-utf8"),
    ]
    entries: list[dict[str, Any]] = []
    for name, payload, rows, columns, expectation in cases:
        path = matrix / name
        write_bytes(path, payload)
        entries.append(
            file_entry(
                f"csv-matrix-{path.stem}",
                path,
                "csv-parser-matrix",
                rows,
                columns,
                {"expectation": expectation},
            )
        )
    long_path = matrix / "long-row.csv"
    long_value = "x" * 1_048_577
    write_text(long_path, f"id,payload\n1,{long_value}\n")
    entries.append(
        file_entry(
            "csv-matrix-long-row",
            long_path,
            "csv-parser-matrix",
            1,
            2,
            {"expectation": "valid", "payloadUtf8Bytes": len(long_value)},
        )
    )
    return entries


def make_profile_csv(root: Path) -> list[dict[str, Any]]:
    profile_path = root / "small" / "csv-profile-types.csv"
    header = ["text", "boolean", "int64", "uint64", "float64", "decimal", "date", "timestamp", "duration", "skip"]
    rows = [
        ["alpha", "true", "-9223372036854775808", "0", "1.5", "123.4500", "2026-07-22", "2026-07-22T01:02:03.123456789Z", "+1d 02:03:04.000000005", "ignored"],
        ["", "false", "9223372036854775807", "18446744073709551615", "NaN", "-0.010", "2024-02-29", "2025-12-18T01:23:34.111111111+09:00", "-00:00:00.000000001", "ignored"],
        [" NULL ", "NULL", "NULL", "NULL", "NULL", "NULL", "NULL", "NULL", "NULL", "ignored"],
    ]
    profile_path.parent.mkdir(parents=True, exist_ok=True)
    partial = profile_path.with_suffix(".csv.partial")
    with partial.open("w", encoding="utf-8", newline="") as stream:
        writer = csv.writer(stream, lineterminator="\n")
        writer.writerow(header)
        writer.writerows(rows)
    partial.replace(profile_path)

    duration_path = root / "small" / "duration-profile.csv"
    duration_rows = [
        ["rawInteger", "ns", "0", "valid", "0"],
        ["rawInteger", "ms", "-42", "valid", "-42"],
        ["daysClock", "ns", "+1d 02:03:04.000000005", "valid", "93784000000005"],
        ["daysClock", "us", "-00:00:00.000001", "valid", "-1"],
        ["daysClock", "ns", "", "empty", ""],
        ["daysClock", "ns", "NULL", "null-token", ""],
        ["daysClock", "ms", "00:00:00.000000001", "invalid-inexact-source-unit", ""],
        ["rawInteger", "s", "1.5", "invalid-not-signed-integer", ""],
        ["daysClock", "ns", "1:02:03", "invalid-hour-width", ""],
        ["daysClock", "ns", "00:00:00junk", "invalid-trailing-junk", ""],
    ]
    with duration_path.open("w", encoding="utf-8", newline="") as stream:
        writer = csv.writer(stream, lineterminator="\n")
        writer.writerow(["input_format", "source_unit", "raw", "expected_state", "expected_count"])
        writer.writerows(duration_rows)
    return [
        file_entry(
            "csv-profile-types",
            profile_path,
            "all-csv-profile-types",
            len(rows),
            len(header),
            {"trim": True, "nullToken": "NULL", "durationSourceUnit": "ns", "durationInputFormat": "daysClock"},
            schema=[{"name": name, "profileType": name.title()} for name in header],
        ),
        file_entry(
            "duration-profile",
            duration_path,
            "duration-grammar",
            len(duration_rows),
            5,
            {
                "daysClockGrammar": "[+|-][<unsigned days>d ]HH:MM:SS[.1..9]",
                "rawIntegerGrammar": "signed decimal integer",
                "sourceUnits": ["s", "ms", "us", "ns"],
            },
        ),
    ]


def make_duration_parquet(root: Path) -> list[dict[str, Any]]:
    small = root / "small"
    counts = [None, 0, 1, -1, 86_400, -86_400, 9_007_199_254_740_991, -(2**63), 2**63 - 1]
    duration_path = small / "duration-arrow.parquet"
    table = pa.table(
        {
            "duration_s": pa.array(counts, type=pa.duration("s")),
            "duration_ms": pa.array(counts, type=pa.duration("ms")),
            "duration_us": pa.array(counts, type=pa.duration("us")),
            "duration_ns": pa.array(counts, type=pa.duration("ns")),
        }
    )
    write_parquet(duration_path, table)
    entries = [
        parquet_entry(
            "duration-arrow",
            duration_path,
            "arrow-duration-units",
            {"counts": counts, "units": ["s", "ms", "us", "ns"], "nullIsEmpty": True, "zeroIsOccupied": True},
        )
    ]

    pandas_path = small / "duration-pandas-metadata.parquet"
    pandas_schema = pa.schema(
        [pa.field("timedelta", pa.duration("ns"), nullable=True)],
        metadata={
            b"pandas": json.dumps(
                {
                    "index_columns": [],
                    "column_indexes": [],
                    "columns": [{"name": "timedelta", "field_name": "timedelta", "pandas_type": "timedelta", "numpy_type": "timedelta64[ns]", "metadata": None}],
                    "creator": {"library": "phase13-fixture-generator", "version": GENERATOR_VERSION},
                    "pandas_version": "2.x-contract",
                },
                separators=(",", ":"),
            ).encode("utf-8")
        },
    )
    pandas_table = pa.Table.from_arrays([pa.array([None, 0, 1, -1, 86_400_000_000_000], type=pa.duration("ns"))], schema=pandas_schema)
    write_parquet(pandas_path, pandas_table)
    entries.append(
        parquet_entry(
            "duration-pandas-metadata",
            pandas_path,
            "pandas-numpy-timedelta-metadata",
            {"counts": [None, 0, 1, -1, 86_400_000_000_000], "unit": "ns"},
        )
    )

    negative_path = small / "duration-negative-types.parquet"
    negative_table = pa.table(
        {
            "physical_int64": pa.array([None, 0, 1, -1], type=pa.int64()),
            "time32_s": pa.array([None, 0, 1, 86_399], type=pa.time32("s")),
            "time64_ns": pa.array([None, 0, 1, 86_399_999_999_999], type=pa.time64("ns")),
            # PyArrow cannot serialize Arrow Interval types to Parquet.  Keep all three
            # physical payload shapes in this negative fixture and record that fact in
            # the oracle rather than pretending a typed Interval round-trip succeeded.
            "interval_year_month_physical": pa.array([None, 0, 1, -1], type=pa.int32()),
            "interval_day_time_physical": pa.array(
                [None, bytes(8), (1).to_bytes(8, "little", signed=True), (-1).to_bytes(8, "little", signed=True)],
                type=pa.binary(8),
            ),
            "interval_month_day_nano_physical": pa.array(
                [None, bytes(16), (1).to_bytes(16, "little", signed=True), (-1).to_bytes(16, "little", signed=True)],
                type=pa.binary(16),
            ),
        }
    )
    write_parquet(negative_path, negative_table)
    entries.append(
        parquet_entry(
            "duration-negative-types",
            negative_path,
            "duration-lookalike-negative-types",
            {
                "durationColumns": [],
                "int64RemainsInteger": True,
                "unsupported": ["time32_s", "time64_ns"],
                "intervalPayloadsArePhysicalOnly": True,
                "pyarrowParquetTypedInterval": "UNSUPPORTED",
            },
        )
    )
    return entries


def make_timestamp_and_wide(root: Path) -> list[dict[str, Any]]:
    small = root / "small"
    timestamp_path = small / "timestamp-zones.parquet"
    epoch_ns = [1_735_690_434_111_111_111, 1_741_506_600_123_456_789, 1_762_066_800_999_999_999]
    table = pa.table(
        {
            "naive": pa.array(epoch_ns, type=pa.timestamp("ns")),
            "utc": pa.array(epoch_ns, type=pa.timestamp("ns", tz="UTC")),
            "fixed_plus_09": pa.array(epoch_ns, type=pa.timestamp("ns", tz="+09:00")),
            "asia_seoul": pa.array(epoch_ns, type=pa.timestamp("ns", tz="Asia/Seoul")),
            "america_new_york": pa.array(epoch_ns, type=pa.timestamp("ns", tz="America/New_York")),
        }
    )
    write_parquet(timestamp_path, table)
    entries = [
        parquet_entry(
            "timestamp-zones",
            timestamp_path,
            "timestamp-timezone-and-nanoseconds",
            {"epochNanoseconds": [str(value) for value in epoch_ns], "timezonePolicy": "preserve source timezone metadata and wall-clock fields"},
        )
    ]
    wide_path = small / "ui-wide-documents.parquet"
    wide = pa.table({f"column_{index:02d}": pa.array([index, index + 100], type=pa.int64()) for index in range(80)})
    write_parquet(wide_path, wide)
    entries.append(parquet_entry("ui-wide-documents", wide_path, "80-visible-logical-columns", {"columnOrder": wide.column_names}))
    copy_path = small / "copy-history-mock.json"
    operations = [
        {"id": f"copy-{index}", "state": state, "reason": reason, "sequence": index}
        for index, (state, reason) in enumerate(
            [("active", None), ("success", None), ("cancelled", "user"), ("failed", "clipboard unavailable"), ("failed", "limit exceeded"), ("failed", "source closed"), ("failed", "stale query"), ("failed", "I/O error")]
        )
    ]
    write_text(copy_path, json.dumps({"operations": operations}, ensure_ascii=False, indent=2) + "\n")
    entries.append(file_entry("copy-history-mock", copy_path, "bounded-copy-history", len(operations), 4, {"visiblePreviousLimit": 5}, kind="json"))
    return entries


LARGE_SCHEMA = pa.schema(
    [
        pa.field("row_id", pa.int64(), nullable=False),
        pa.field("group_id", pa.int64(), nullable=False),
        pa.field("category", pa.string(), nullable=False),
        pa.field("active", pa.bool_(), nullable=False),
        pa.field("optional_value", pa.int32(), nullable=True),
        pa.field("event_time", pa.timestamp("ns", tz="UTC"), nullable=False),
        pa.field("amount", pa.float64(), nullable=False),
        pa.field("label", pa.string(), nullable=False),
        pa.field("code", pa.string(), nullable=False),
        *[pa.field(f"metric_{index:02d}", pa.int64(), nullable=False) for index in range(6)],
    ]
)


def large_columns(start: int, count: int, cardinality: str) -> dict[str, Iterable[Any]]:
    indices = np.arange(start, start + count, dtype=np.int64)
    mixed = stable_u64_array(indices, 101)
    if cardinality == "low":
        group = indices % 128
        category = [f"category-{value:02d}" for value in indices % 16]
        label = [f"label-{value:03d}" for value in indices % 256]
        code = [f"code-{value:02d}" for value in indices % 64]
    else:
        group = (mixed & np.uint64(0x7FFF_FFFF_FFFF_FFFF)).astype(np.int64)
        category = [f"category-{int(value):016x}" for value in mixed]
        labels = stable_u64_array(indices, 211)
        codes = stable_u64_array(indices, 307)
        label = [f"label-{int(value):016x}" for value in labels]
        code = [f"code-{int(value):016x}" for value in codes]
    optional = (indices % 10_000).astype(np.int32)
    return {
        "row_id": indices,
        "group_id": group,
        "category": category,
        "active": indices % 2 == 0,
        "optional_value": pa.array(optional, mask=indices % 97 == 0, type=pa.int32()),
        "event_time": pa.array(1_700_000_000_000_000_000 + indices * 1_000_003, type=pa.timestamp("ns", tz="UTC")),
        "amount": (mixed % np.uint64(10_000_000)).astype(np.float64) / 100.0,
        "label": label,
        "code": code,
        **{f"metric_{column:02d}": (indices * (column + 3) + column * 17) % (10_000 + column * 101) for column in range(6)},
    }


def large_batch(start: int, count: int, cardinality: str) -> pa.RecordBatch:
    columns = large_columns(start, count, cardinality)
    arrays = [pa.array(columns[field.name], type=field.type) for field in LARGE_SCHEMA]
    return pa.RecordBatch.from_arrays(arrays, schema=LARGE_SCHEMA)


def write_large_csv(path: Path, cardinality: str, malformed_last_row: bool) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    partial = path.with_suffix(path.suffix + ".partial")
    with partial.open("w", encoding="utf-8", newline="", buffering=8 * 1024 * 1024) as stream:
        stream.write(",".join(LARGE_SCHEMA.names) + "\n")
        for start in range(0, LARGE_ROWS, LARGE_BATCH_ROWS):
            count = min(LARGE_BATCH_ROWS, LARGE_ROWS - start)
            columns = large_columns(start, count, cardinality)
            lines: list[str] = []
            for offset in range(count):
                row = start + offset
                optional = "" if row % 97 == 0 else str(row % 10_000)
                label = str(columns["label"][offset])
                if malformed_last_row and row == LARGE_ROWS - 1:
                    label = '"' + ("x" * 1_048_577)
                values = [
                    str(row),
                    str(columns["group_id"][offset]),
                    str(columns["category"][offset]),
                    "true" if row % 2 == 0 else "false",
                    optional,
                    str(1_700_000_000_000_000_000 + row * 1_000_003),
                    f"{float(columns['amount'][offset]):.2f}",
                    label,
                    str(columns["code"][offset]),
                    *[str(int(columns[f"metric_{column:02d}"][offset])) for column in range(6)],
                ]
                lines.append(",".join(values))
            stream.write("\n".join(lines) + "\n")
            print(f"[{path.name}] {start + count:,}/{LARGE_ROWS:,}", file=sys.stderr, flush=True)
    partial.replace(path)


def write_large_parquet(path: Path, cardinality: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    partial = path.with_suffix(path.suffix + ".partial")
    partial.unlink(missing_ok=True)
    writer = pq.ParquetWriter(partial, LARGE_SCHEMA, compression="zstd", compression_level=3, use_dictionary=True, data_page_version="2.0")
    try:
        for start in range(0, LARGE_ROWS, PARQUET_ROW_GROUP_ROWS):
            count = min(PARQUET_ROW_GROUP_ROWS, LARGE_ROWS - start)
            writer.write_batch(large_batch(start, count, cardinality), row_group_size=count)
            print(f"[{path.name}] {start + count:,}/{LARGE_ROWS:,}", file=sys.stderr, flush=True)
    finally:
        writer.close()
    partial.replace(path)


def make_large(root: Path) -> list[dict[str, Any]]:
    entries: list[dict[str, Any]] = []
    for cardinality in ("low", "high"):
        csv_path = root / "large" / f"csv-{LARGE_ROWS}-{cardinality}.csv"
        if not csv_path.exists():
            write_large_csv(csv_path, cardinality, False)
        entries.append(file_entry(f"csv-{LARGE_ROWS}-{cardinality}", csv_path, f"{cardinality}-cardinality-15-column", LARGE_ROWS, LARGE_COLUMNS, {"rowIdRange": [0, LARGE_ROWS - 1], "malformedRows": []}, schema=schema_json(LARGE_SCHEMA)))
        parquet_path = root / "large" / f"boundary-{LARGE_ROWS}-{cardinality}.parquet"
        if not parquet_path.exists():
            write_large_parquet(parquet_path, cardinality)
        entries.append(parquet_entry(f"boundary-{LARGE_ROWS}-{cardinality}", parquet_path, f"{cardinality}-cardinality-15-column", {"rowIdRange": [0, LARGE_ROWS - 1], "rowFunction": "stable_u64(index, salt)"}))
    invalid_path = root / "large" / f"csv-{LARGE_ROWS}-long-invalid.csv"
    if not invalid_path.exists():
        write_large_csv(invalid_path, "low", True)
    entries.append(file_entry(f"csv-{LARGE_ROWS}-long-invalid", invalid_path, "low-cardinality-final-long-malformed-row", LARGE_ROWS, LARGE_COLUMNS, {"malformedRows": [LARGE_ROWS - 1], "malformedPayloadBytes": 1_048_577, "error": "unclosed quote at final logical row"}, schema=schema_json(LARGE_SCHEMA)))
    return entries


def ensure_large_path_is_safe(workspace: Path, output: Path) -> None:
    relative = output.resolve().relative_to(workspace.resolve())
    if len(relative.parts) < 2 or relative.parts[0] != ".tmp" or not relative.parts[1].startswith("phase13-"):
        raise ValueError("--large output must be below .tmp/phase13-*")


def clean_owned_outputs(root: Path) -> None:
    if not root.exists():
        return
    for child in root.iterdir():
        if child.name in {"small", "large"}:
            shutil.rmtree(child)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--output-dir", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--manifest", type=Path, default=DEFAULT_MANIFEST)
    parser.add_argument("--large", action="store_true", help="also generate the 5,850,000-row fixtures")
    parser.add_argument("--clean", action="store_true", help="remove only this generator's small/large output directories first")
    return parser.parse_args()


def main() -> int:
    args = parse_args()
    workspace = Path(__file__).resolve().parents[1]
    output = (workspace / args.output_dir).resolve() if not args.output_dir.is_absolute() else args.output_dir.resolve()
    manifest_path = (workspace / args.manifest).resolve() if not args.manifest.is_absolute() else args.manifest.resolve()
    if args.large:
        ensure_large_path_is_safe(workspace, output)
    output.mkdir(parents=True, exist_ok=True)
    if args.clean:
        clean_owned_outputs(output)

    fixtures: list[dict[str, Any]] = []
    fixtures.append(make_boundary_states(output))
    fixtures.append(make_boundary_query_map(output))
    fixtures.append(make_boundary_long_string(output))
    fixtures.extend(make_csv_matrix(output))
    fixtures.extend(make_profile_csv(output))
    fixtures.extend(make_duration_parquet(output))
    fixtures.extend(make_timestamp_and_wide(output))
    if args.large:
        fixtures.extend(make_large(output))

    generator_path = Path(__file__).resolve()
    manifest = {
        "schemaVersion": 1,
        "generatorVersion": GENERATOR_VERSION,
        "generator": generator_path.as_posix(),
        "generatorSha256": sha256_file(generator_path),
        "seed": SEED,
        "generatedAtUtc": utc_now(),
        "outputDirectory": output.as_posix(),
        "largeIncluded": args.large,
        "environment": {"python": platform.python_version(), "numpy": np.__version__, "pyarrow": pa.__version__, "platform": platform.platform()},
        "configuration": {"largeRows": LARGE_ROWS, "largeColumns": LARGE_COLUMNS, "largeBatchRows": LARGE_BATCH_ROWS, "parquetRowGroupRows": PARQUET_ROW_GROUP_ROWS, "compression": "zstd"},
        "fixtures": fixtures,
        "summary": {"fixtureCount": len(fixtures), "bytes": sum(entry["bytes"] for entry in fixtures), "allAuditsPass": all(entry["audit"] == "PASS" for entry in fixtures)},
        "validation": "PASS",
    }
    manifest_path.parent.mkdir(parents=True, exist_ok=True)
    manifest_path.write_text(json.dumps(manifest, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(json.dumps({"manifest": manifest_path.as_posix(), "fixtures": len(fixtures), "bytes": manifest["summary"]["bytes"], "large": args.large}))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
